### ISSUE TITLE
Audit all CNCF docs projects for correct license documents

### ISSUE THREAD

**Issue by celestehorgan** [cncf/techdocs#22]
Per https://github.com/cncf/techdocs/blob/main/howto/repo-setup.md#license-files and https://github.com/cncf/project-template/pull/12, use the project tracking spreadsheet to audit existing projects for license compliance.

Questions to answer prior to starting this task:

- Do we want to bring old projects into compliance or only tackle new ones?
- Do we want to note any exceptions to the license rules somewhere?

**Comment by caniszczyk** [comment]
The simple thing here is if you come across a website/docs ONLY repo in CNCF and it has the Apache License attached to it, add a LICENSE-DOCS file that's CC-BY 4.0 , that's the fix here imho

**Comment by chalin** [comment]
Legal matters are hard, and they are even harder when there are **multiple sources of (partial) truth**, so I'd like to suggest that we avoid duplication/repetition at all costs. IMHO:

- All projects should have a **single LICENSE file** that contains _all the license terms_ for the repo. For examples see:
  - https://github.com/etcd-io/website/blob/main/LICENSE
  - https://github.com/grpc/grpc.io/blob/main/LICENSE
  - https://github.com/notaryproject/notaryproject.dev/blob/main/LICENSE
- **Avoid repeating license info in the repo's README** (as is suggested in https://github.com/cncf/techdocs/blob/main/howto/repo-setup.md#license-files) otherwise that creates multiple sources of (partial) truth, potential conflicts, possible misinterpretations etc.
  
  GitHub already prominently links to _the_ LICENSE file in the repo's **About** section:

  > <img width="890" alt="Screen Shot 2021-11-03 at 11 46 39 AM" src="https://user-images.githubusercontent.com/4140793/140094860-88f5af3e-d856-4b2e-8990-efda5b6e92a9.png">

  If y'all feel the need to mention the license in the README, then we should do so via a single link using text similar to that used by GitHub (while avoiding to mention the license kind since that might change), something like this:
  
  > View [license](LICENSE.md)

/cc @nate-double-u

**Comment by chalin** [comment]
I just noticed that we have license terms explicitly documented already in https://github.com/cncf/techdocs/blob/main/howto/repo-setup.md: 

> Unless otherwise specified, documentation for CNCF projects is licensed under CC-BY-4.0. 
> Code is licensed under Apache 2.0.

I just submitted a proposed single LICENSE file that could be used by all CNCF projects, see https://github.com/cncf/project-template/pull/17. If we can adopt a single (verbatim) license file for all projects, then auditing will become that much easier. As the number of CNCF projects increasing, this will scale much better IMHO.

Thoughts?

**Comment by chalin** [comment]
I guess that the audit should be conducted in light of the exceptions documented in https://github.com/cncf/foundation/tree/master/license-exceptions?

**Comment by nate-double-u** [comment]
Does clomontior cover this?
@amye, since you're assigned.

**Comment by amye** [comment]
This is from 2021. I'm not sure this is still relevant, given as the charter says cc-by-4.0 for docs.

**Comment by nate-double-u** [comment]
Fair enough, closing as stale.
